### ISSUE TITLE
No root permission, no permission to install k3d

### ISSUE THREAD

**Issue by yJunS** [kubesphere-sigs/ks#201]
When I use not root permission and install k3d, tips no permission. but when the user has `![image](https://user-images.githubusercontent.com/20575981/132883990-564cbb88-73e2-4ec0-81ff-a0991b8cfbc8.png)do` permission, `sudo ks install k3d` is ok.
![no permission install](https://user-images.githubusercontent.com/20575981/132882056-75d14974-a456-4e0b-9be1-c6bcf197d856.png)

![sudo user install](https://user-images.githubusercontent.com/20575981/132883773-c87d61e4-3d06-44ce-8e02-7e7c2dc4ccc7.png)

So I suggest describing the installation method clearly.

**Comment by LinuxSuRen** [comment]
I don't think it's necessary. It's common sense.

**Comment by yJunS** [comment]
What I want to express is like when Kubernetes installs kubeadmin, this is the case.
![image](https://user-images.githubusercontent.com/20575981/133104742-d1640f5d-7229-4234-84de-a45724e60393.png)
